### ISSUE TITLE
Better error handling with ProviderSignInController

### ISSUE THREAD

**Issue by codelirium** [spring-projects/spring-social#153]
The ProviderSignInController contains some handlers which can throw exceptions not handled properly.
For example: connectionFactoryLocator.getConnectionFactory(providerId) appears to be throwing an IllegalArgumentException which is not caught within the handler's scope to return provide the redirection url but rather gives back a shouty 500.
I will fork the repo soon and provide a pull request with a candidate solution.

**Comment by codelirium** [comment]
Pull request for a fix @ https://github.com/spring-projects/spring-social/pull/154

Kindest regards,
Stavros Lekkas (@codelirium)

**Comment by habuma** [comment]
Merged the PR and it should be available in the latest 1.1.1.BUILD-SNAPSHOT. Will produce a 1.1.1.RELEASE build soon.
