### ISSUE TITLE
Sping framework version issue

### ISSUE THREAD

**Issue by cigaly** [spring-projects/spring-social#161]
Spring Framework version in gradle.properties should be 4.1.6, not 4.1.6.BUILD-SNAPSHOT. At least in release version of Spring Social.

**Comment by cemo** [comment]
@habuma can you fix this issue:

You can see details here: https://repo1.maven.org/maven2/org/springframework/social/spring-social-core/1.1.1.RELEASE/spring-social-core-1.1.1.RELEASE.pom

**Comment by cigaly** [comment]
... and also:
https://repo1.maven.org/maven2/org/springframework/social/spring-social-security/1.1.1.RELEASE/spring-social-security-1.1.1.RELEASE.pom
and
https://repo1.maven.org/maven2/org/springframework/social/spring-social-web/1.1.1.RELEASE/spring-social-web-1.1.1.RELEASE.pom

**Comment by habuma** [comment]
Doh! I know why that happened and I should've caught it. That'll teach me to cut a release when I only have a short window of time. Will fix it, although it will require a 1.1.2.RELEASE (can't change what's there for 1.1.1, unfortunately). Hang tight...it will be ready very soon.

**Comment by habuma** [comment]
Spring Social (core/web/security/config) 1.1.2.RELEASE is now available in Maven central and no longer depends on Spring 4.1.6.BUILD-SNAPSHOT.
