### ISSUE TITLE
UserConnection table encryption support for sensitive columns

### ISSUE THREAD

**Issue by codelirium** [spring-projects/spring-social#162]
Hello,

I was thinking that maybe it is a good idea if we encrypt sensitive information in the UserConnection table as any leak could enable a malicious attacker to highjack social sessions.

That seems a straightforward change in the spring-social-core social/connect/jdbc area however that might be more tricky to migrate existing rows in a one-off manner.

What is your view on this? If this feature puts value to the project, what technical guidelines would you provide? I will then try to provide a pull request.

Kind regards,
Stavros

**Comment by codelirium** [comment]
Looking closer into this I think the TextEncryptor is what Iam looking for. If so, this issue can be closed without any action.

**Comment by habuma** [comment]
It looks like you've discovered the answer for yourself. It's up to the connection repository implementation to ensure that sensitive data is encrypted. In the case of the JDBC connection repositories, they are given a TextEncryptor for that purpose. For development/testing purposes, a plain-text (e.g., a no-op) encryptor is fine, but for a production app, you'll want to pick a strong encryptor. (Tip: You can use Spring profiles to select the appropriate TextEncryptor bean at runtime.)
