### ISSUE TITLE
ProviderSignInUtils API desync with docs

### ISSUE THREAD

**Issue by jfhs** [spring-projects/spring-social#171]
It seems that ProviderSignInUtils API has changed from static methods to interface, but <a href="http://docs.spring.io/spring-social/docs/1.1.2.RELEASE/reference/htmlsingle/#section_signUpForm">docs</a> still use old version which made me confused for some time.

If that will help, I solved it in straight forward way (probably not the best) in my SocialConfigurer added
```java
@Autowired
ConnectionFactoryLocator connectionFactoryLocator;

@Bean
public ProviderSignInUtils providerSignInUtils() {
   return new ProviderSignInUtils(connectionFactoryLocator, getUsersConnectionRepository(connectionFactoryLocator));
}
```
And just AutoWired it in controller where I needed it:
```java
@Autowired
private ProviderSignInUtils signInUtils;
```

**Comment by habuma** [comment]
Fixed in latest code. Will be part of next release.
