### ISSUE TITLE
SocialUserDetailsService throws DataAccessException

### ISSUE THREAD

**Issue by dlvenable** [spring-projects/spring-social#173]
Why does SocialUserDetailsService.loadUserByUserId() declare that it throws a DataAccessException? I don't see the code specifically handling this exception. Can this be removed? This creates a dependency on the Spring Framework transactions project which seems unnecessary. The only other such dependency is on the JDBC connection classes, but these do not need to be used if you are creating your own connection classes.

As seen here:
https://github.com/spring-projects/spring-social/blob/1.1.2.RELEASE/spring-social-security/src/main/java/org/springframework/social/security/SocialUserDetailsService.java#L34

**Comment by bytor99999** [comment]
My initial guess would be because the interface from Spring Security that it implements declares that it throws UserNotFoundException which is a subclass of DataAccessException.

Method Detail

 <>loadUserByUsername
UserDetails <http://docs.spring.io/autorepo/docs/spring-security/3.2.2.RELEASE/apidocs/org/springframework/security/core/userdetails/UserDetails.html> loadUserByUsername(String <http://download.oracle.com/javase/6/docs/api/java/lang/String.html?is-external=true> username)
                               throws UsernameNotFoundException <http://docs.spring.io/autorepo/docs/spring-security/3.2.2.RELEASE/apidocs/org/springframework/security/core/userdetails/UsernameNotFoundException.html>


Thanks

Mark

**Comment by dlvenable** [comment]
@bytor99999 The SocialUserDetailsService, while sharing the same basic name as UserDetailsService, does not inherit from it. Regardless, UserDetailsService throws a UsernameNotFoundException, which inherits from AuthenticationException - a Spring Security exception.

**Comment by bytor99999** [comment]
I see what you mean, this is an interface in Spring Social. However, it is so close to Spring Security that it still throws a Spring Security exception.

SocialUserDetails <http://docs.spring.io/spring-social/docs/current/apidocs/org/springframework/social/security/SocialUserDetails.html> loadUserByUserId(String <http://download.oracle.com/javase/6/docs/api/java/lang/String.html?is-external=true> userId)
                                   throws org.springframework.security.core.userdetails.UsernameNotFoundException,
                                          DataAccessException <http://static.springframework.org/spring/docs/3.2.x/javadoc-api/org/springframework/dao/DataAccessException.html?is-external=true>


So, it is not a direct implementation or extension. Thanks for clarifying that for me.

Mark

**Comment by dlvenable** [comment]
SocialUserDetailsService.loadUserByUserId() declares that it throws two exceptions:
1. UsernameNotFoundException
2. DataAccessException

UsernameNotFoundException inherits from AuthenticationException which inherits from RuntimeException. Thus it only requires Spring Security.

DataAccessException is part of Spring DAO.

I suggest keeping UsernameNotFoundException and removing DataAccessException from SocialUserDetailsService.loadUserByUserId().

**Comment by dlvenable** [comment]
I made the change locally and was able to build the Spring Social project. This change would affect other clients though because existing implementations would be adding an additional throws to an overridden method.

Here is what it looks like:
SocialUserDetails loadUserByUserId(String userId) throws UsernameNotFoundException;

**Comment by habuma** [comment]
FYI: I've removed DataAccessException from the throws clause. I recognize that anyone who has implemented this will now have broken code, so it will be documented. But I felt the impact was minimal and the removal important enough to make the breaking change.

**Comment by dlvenable** [comment]
@habuma, thank you for removing it from the throws clause. I think this will certainly help keep the code and client projects cleaner.
