### ISSUE TITLE
Set scope not being used in built OAuth2 URL

### ISSUE THREAD

**Issue by andrewferk** [spring-projects/spring-social#178]
I followed the [guide](http://docs.spring.io/spring-social/docs/1.1.2.RELEASE/reference/htmlsingle/#section_implementing) for implementing my own provider and have used others as a reference. We require a scope to be provided when hitting our OAuth2 endpoints, and I'd prefer if the scope can be configured when we create our connection factory:

```java
MyConnectionFactory mycf = new MyConnectionFactory("clientId", "clientSecret");
mycf.setScope("myApi");
cfConfig.addConnectionFactory(mycf);
```

However, this scope never makes it to the `OAuth2AuthenticationService`. When [`OAuth2AuthenticationService#setScope`](https://github.com/spring-projects/spring-social/blob/master/spring-social-security/src/main/java/org/springframework/social/security/provider/OAuth2AuthenticationService.java#L127-L134) executes, [`defaultScope`](https://github.com/spring-projects/spring-social/blob/master/spring-social-security/src/main/java/org/springframework/social/security/provider/OAuth2AuthenticationService.java#L48) is still an empty string. The `defaultScope` is supposed to be set within [`SecurityEnabledConnectionFactoryConfigurer#wrapAsAuthenticationService`](https://github.com/spring-projects/spring-social/blob/master/spring-social-config/src/main/java/org/springframework/social/config/annotation/SecurityEnabledConnectionFactoryConfigurer.java#L49-L58), but nothing seems to get executed after the [`final OAuth2AuthenticationService<A> authService = ...`](https://github.com/spring-projects/spring-social/blob/master/spring-social-config/src/main/java/org/springframework/social/config/annotation/SecurityEnabledConnectionFactoryConfigurer.java#L53) line (I set breakpoints, logs and system out).

I don't know what could be preventing the next line to be run, but because it's not running the default scope is never being set.

The workaround is to set the scope as a url parameter, but I'd prefer this to be coded in config.

**Comment by habuma** [comment]
This is odd. In all of the tests I've run, it does make it to that next line and the default scope is set. Would it be possible for you to share what you have (or some facsimile thereof) for me to try? 

I can't think of too many things that would prevent that line from running. The only 2 I've come up with are:

 (1) An exception is thrown from the previous line where OAuth2AuthenticationService is created. (Even then, I can't imagine what exception would be thrown)
 (2) Maybe you are seeing this behavior in a debugger that is showing the current version of the code but the actual executable in play is an older version that doesn't have that line. I've had this kind of thing happen to me from time to time and it can be terribly confusing. If the method is returning immediately after that "final" line, I'd bet that this is what's happening.

**Comment by andrewferk** [comment]
Thanks. It was (2). I was using an outdated version of [spring-social-samples](https://github.com/spring-projects/spring-social-samples/tree/master/spring-social-showcase-sec) that was still referencing spring social 1.1.0.
