### ISSUE TITLE
Change Spring Security dependency back to 3.2.x

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-social#184]
1.1.3.RELEASE moved from Spring Security 3.2.x to 4.0.x. While it's only an optional dependency and, therefore, doesn't affect an application's transitive dependencies, it introduces the risk of making a new maintenance release of Spring Social force users to move to a new major version of Spring Security. To avoid this risk, Spring Social should continue to compile against Spring Security 3.2.x.

**Comment by habuma** [comment]
Rolled the dependency back to Spring Security 3.2.9.RELEASE. Already in latest snapshot build. Will be in 1.1.4.RELEASE.
