### ISSUE TITLE
Latest release is not including latest source

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-social#186]
The branch you used to release 1.1.3 is not including latest master. 

Also you forget upgrading to 1.1.4.BUILD-SNAPSHOT.

**Comment by okohub** [comment]
+1

some codes are not included in 1.1.3 release. why did you release from a specific point?

**Comment by habuma** [comment]
The 1.1.3 release was produced quickly to address a security concern. The code in master hadn't been fully vetted yet, so I felt uncomfortable releasing it along with the security fix and the urgency of the security fix didn't allow me time to test the code in master. 

And I fixed the build to build 1.1.4.BUILD-SNAPSHOT earlier today, probably at around the same time you reported it.

There will be a 1.1.4 release soon which will include those items in master.
