### ISSUE TITLE
1.1.3 references httpclient 4.4 and higher but accepts earlier versions and bombs

### ISSUE THREAD

**Issue by mschipperheyn** [spring-projects/spring-social#187]
If you use httpclient 4.3.x, you will get 
java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy

I suggest adding the 4.4 requirement to the pom

**Comment by trisberg** [comment]
Looks like this is related to https://github.com/spring-projects/spring-social/issues/147

**Comment by habuma** [comment]
I've already changed this to reference httpclient 4.3.6 and that change will be in 1.1.4.RELEASE (expected later today or Monday).
