### ISSUE TITLE
ArrayIndexOutOfBoundsException in UserProfileBuilder when name is empty String

### ISSUE THREAD

**Issue by arminrosu** [spring-projects/spring-social#240]
### Summary

UserProfileBuilder throws an error when trying to create a profile with an empty string `""` as a name.

### Actual Behavior

`java.lang.ArrayIndexOutOfBoundsException: 0`

This error is caused by [this line](https://github.com/spring-projects/spring-social/blob/7eeae96e0d2a146283123a0213acccad86528f2b/spring-social-core/src/main/java/org/springframework/social/connect/UserProfileBuilder.java#L122).

### Expected Behavior

It should return a profile with an empty firstName and empty lastName, as it does when setting the name to `null`.

### Configuration

Default

### Version

Latest

### Sample

```java
UserProfile user = new UserProfileBuilder().setName("");
```

```java
UserProfile user = UserProfileBuilder().setName(facebook.userOperations().getUserProfile().getName());
```

**Comment by AndriyBrez** [comment]
@arminrosu your bug doesn't reproduce. The code works as expected without any exceptions:
```java
@Test
public void shouldReturnEmptyUserName() {
	UserProfileBuilder userProfileBuilder = new UserProfileBuilder().setName("");
	UserProfile user = userProfileBuilder.build();
	assertEquals("", user.getFirstName());
	assertNull(user.getLastName());
}
```

**Comment by arminrosu** [comment]
That seems right. Wondering how the error appeared. Closing for now as it seems to not apply. Thanks @AndriyBrez
