### ISSUE TITLE
Release Spring boot 2 compatible version

### ISSUE THREAD

**Issue by pcornelissen** [spring-projects/spring-social#249]
Version 3 is in milestone stage for quite a while and spring boot 2 is out now.
It would be nice to have a stable release based on the current version 3.x of spring social, because especially for the facebook connector versions below 3.x don't work because the API has changed

**Comment by adlmez** [comment]
+1

**Comment by Mike-the-one** [comment]
+1

**Comment by Mike-the-one** [comment]
Where is milestone 3?  I only see 2.0.0 in `http://repo.spring.io/milestone`.  Is social 3.x compatible with spring boot 2.0?

**Comment by tayfunyasar** [comment]
+1

**Comment by happymzw** [comment]
+1

**Comment by pcornelissen** [comment]
No reaction at all from the maintainers? :-(

**Comment by pcornelissen** [comment]
It looks like spring social is in the attic now.
Login is possible via spring security oauth client, if you want to do more, you might want to have a look at restFB

**Comment by pcornelissen** [comment]
There is no need to +1 here, spring social is dead
